apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: ticketing.dev
      http:
        paths:
          - path: /api/users/?(.*)
            pathType: ImplementationSpecific  # Required in the new version
            backend:
              service:
                name: auth-srv  # Correct field for service name
                port:
                  number: 3000  # Correct field for service port
          - path: /api/tickets/?(.*)
            pathType: ImplementationSpecific  # Required in the new version
            backend:
              service:
                name: tickets-srv  # Correct field for service name
                port:
                  number: 3000  # Correct field for service port
          - path: /?(.*)
            pathType: ImplementationSpecific  # ✅ Required
            backend:
              service:
                name: client-srv              # ✅ New syntax
                port:
                  number: 3000
